### ISSUE TITLE
Button Dark Theme not working

### ISSUE THREAD

**Issue by SyaFR** [zuramai/mazer#90] opened 2022-06-04 23:56 UTC
Components Button dark theme not working

**Comment by zuramai** [comment] 2022-06-05 08:12
Duplicate of #89

**Closed by zuramai** 2022-06-05 08:12 UTC

**Comment by SyaFR** [comment] 2022-06-05 12:48
[relase page them](https://github.com/zuramai/mazer/releases) Button dark theme not working in Releases page template.zip
